name: Bump Go Version and stdlibs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6

      - name: Run bump-go
        uses: dduzgun-security/bump-go@f1570383c1d193fb631d1de63a14c665365f178b
        with:
          go_version: ".go-version"
          pr_reviewer: "dduzgun-security"
          github_token: ${{ secrets.GITHUB_TOKEN }}
